version: "3.8"

services:
  cycleops:
    build: .
    environment:
      CYCLEOPS_BASE_URL: ${CYCLEOPS_BASE_URL}
      CYCLEOPS_API_KEY: ${CYCLEOPS_API_KEY}
    volumes:
      - .:/usr/src/app
    network_mode: host
    image: cycleops:latest
    command: sleep infinity
