name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry==1.4.0
    - uses: actions/setup-python@v4
      with:
          python-version: '3.11'
          cache: 'poetry'
    - run: poetry check
    - run: poetry install
    - name: Build and publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --build
