name: Release

on:
  release:
    types: [created]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry==1.4.0
    - uses: actions/setup-python@v4
      with:
          python-version: '3.11'
          cache: 'poetry'
    - run: poetry check
    - run: poetry install
    - name: Build and publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --build

  ghcr:
    name: Publish to GHCR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        push: true
        target: cli
        platforms: linux/amd64,linux/arm64/v8
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/stackmasters/cycleops:${{ github.event.release.name }}
          ghcr.io/stackmasters/cycleops:latest
